# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protobuffer/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protobuffer/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aProtobuffer/messages.proto\"8\n\x0eIdentification\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\"\n\x0e\x41\x63tuatorStatus\x12\x10\n\x08turnedOn\x18\x04 \x01(\x08\"\x1d\n\tTurnOnOff\x12\x10\n\x08turnedOn\x18\x05 \x01(\x08\"W\n\x15\x41irConditioningStatus\x12\x10\n\x08turnedOn\x18\x06 \x01(\x08\x12\x13\n\x0btemperature\x18\x07 \x01(\x05\x12\x17\n\x0froomTemperature\x18\x08 \x01(\x05\".\n\x08setValue\x12\x11\n\teventType\x18\t \x01(\t\x12\x0f\n\x07payload\x18\n \x01(\x01\x32;\n\x0e\x45xampleService\x12)\n\x05GetId\x12\x0f.Identification\x1a\x0f.Identificationb\x06proto3'
)




_IDENTIFICATION = _descriptor.Descriptor(
  name='Identification',
  full_name='Identification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Identification.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Identification.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='Identification.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=86,
)


_ACTUATORSTATUS = _descriptor.Descriptor(
  name='ActuatorStatus',
  full_name='ActuatorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turnedOn', full_name='ActuatorStatus.turnedOn', index=0,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=122,
)


_TURNONOFF = _descriptor.Descriptor(
  name='TurnOnOff',
  full_name='TurnOnOff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turnedOn', full_name='TurnOnOff.turnedOn', index=0,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=153,
)


_AIRCONDITIONINGSTATUS = _descriptor.Descriptor(
  name='AirConditioningStatus',
  full_name='AirConditioningStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turnedOn', full_name='AirConditioningStatus.turnedOn', index=0,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='AirConditioningStatus.temperature', index=1,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomTemperature', full_name='AirConditioningStatus.roomTemperature', index=2,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=242,
)


_SETVALUE = _descriptor.Descriptor(
  name='setValue',
  full_name='setValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventType', full_name='setValue.eventType', index=0,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='setValue.payload', index=1,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=290,
)

DESCRIPTOR.message_types_by_name['Identification'] = _IDENTIFICATION
DESCRIPTOR.message_types_by_name['ActuatorStatus'] = _ACTUATORSTATUS
DESCRIPTOR.message_types_by_name['TurnOnOff'] = _TURNONOFF
DESCRIPTOR.message_types_by_name['AirConditioningStatus'] = _AIRCONDITIONINGSTATUS
DESCRIPTOR.message_types_by_name['setValue'] = _SETVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identification = _reflection.GeneratedProtocolMessageType('Identification', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFICATION,
  '__module__' : 'Protobuffer.messages_pb2'
  # @@protoc_insertion_point(class_scope:Identification)
  })
_sym_db.RegisterMessage(Identification)

ActuatorStatus = _reflection.GeneratedProtocolMessageType('ActuatorStatus', (_message.Message,), {
  'DESCRIPTOR' : _ACTUATORSTATUS,
  '__module__' : 'Protobuffer.messages_pb2'
  # @@protoc_insertion_point(class_scope:ActuatorStatus)
  })
_sym_db.RegisterMessage(ActuatorStatus)

TurnOnOff = _reflection.GeneratedProtocolMessageType('TurnOnOff', (_message.Message,), {
  'DESCRIPTOR' : _TURNONOFF,
  '__module__' : 'Protobuffer.messages_pb2'
  # @@protoc_insertion_point(class_scope:TurnOnOff)
  })
_sym_db.RegisterMessage(TurnOnOff)

AirConditioningStatus = _reflection.GeneratedProtocolMessageType('AirConditioningStatus', (_message.Message,), {
  'DESCRIPTOR' : _AIRCONDITIONINGSTATUS,
  '__module__' : 'Protobuffer.messages_pb2'
  # @@protoc_insertion_point(class_scope:AirConditioningStatus)
  })
_sym_db.RegisterMessage(AirConditioningStatus)

setValue = _reflection.GeneratedProtocolMessageType('setValue', (_message.Message,), {
  'DESCRIPTOR' : _SETVALUE,
  '__module__' : 'Protobuffer.messages_pb2'
  # @@protoc_insertion_point(class_scope:setValue)
  })
_sym_db.RegisterMessage(setValue)



_EXAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='ExampleService',
  full_name='ExampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=292,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetId',
    full_name='ExampleService.GetId',
    index=0,
    containing_service=None,
    input_type=_IDENTIFICATION,
    output_type=_IDENTIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESERVICE)

DESCRIPTOR.services_by_name['ExampleService'] = _EXAMPLESERVICE

# @@protoc_insertion_point(module_scope)
